# 根据 tags 作为关键词为每一篇文章在线搜索封面
article:
  auto_cover: true

  # npm i hexo-related-popular-posts  相关文章推荐功能
  related_posts:
    enable: true
    title: 您可能感兴趣的文章

sidebar:
  menu:
    more: '[更多](/more/)'
